version: '3.8'

services:
  dev:
    container_name: mec-energia-web-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
